-- begin CUBADBVIEWS_ORDER
alter table CUBADBVIEWS_ORDER add constraint FK_CUBADBVIEWS_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references CUBADBVIEWS_CUSTOMER(ID)^
create index IDX_CUBADBVIEWS_ORDER_ON_CUSTOMER on CUBADBVIEWS_ORDER (CUSTOMER_ID)^
-- end CUBADBVIEWS_ORDER
-- begin CUBADBVIEWS_ORDER_ITEM
alter table CUBADBVIEWS_ORDER_ITEM add constraint FK_CUBADBVIEWS_ORDER_ITEM_ON_ORDER foreign key (ORDER_ID) references CUBADBVIEWS_ORDER(ID)^
alter table CUBADBVIEWS_ORDER_ITEM add constraint FK_CUBADBVIEWS_ORDER_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references CUBADBVIEWS_PRODUCT(ID)^
create index IDX_CUBADBVIEWS_ORDER_ITEM_ON_ORDER on CUBADBVIEWS_ORDER_ITEM (ORDER_ID)^
create index IDX_CUBADBVIEWS_ORDER_ITEM_ON_PRODUCT on CUBADBVIEWS_ORDER_ITEM (PRODUCT_ID)^
-- end CUBADBVIEWS_ORDER_ITEM
